{% set name = "ALM" %}
{% set version = "2.0.0_dev.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jochym/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 407084e9bea3c3662455a61775f0712b636b53b6fe75cc0aa2d87e698f8f4f55
  patches:
    - use_external_spglib.patch

build:
  number: 8
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - python
    - liblapack
    - numpy
    - libboost-python-devel
    - eigen
    - spglib >=1.12
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test/*.dat
    - test/*.py
  imports:
    - alm
  commands:
    - cd test
    - python Si_fitting.py
    - python SiC_fitting.py

about:
  home: https://github.com/ttadano/ALM
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Software for calculating harmonic and anharmonic interatomic force constants in solids and molecules.

  description: |
    ALM can be used for Extraction of harmonic and anharmonic force constants 
    based on the supercell approach. It is applicable to any crystal structure
    and low-dimensional systems. Features accurate treatment of translational 
    and rotational invariance and Interface to VASP, Quantum-ESPRESSO, and xTAPP.
  doc_url: http://alm.readthedocs.io/
  dev_url: https://github.com/ttadano/ALM

extra:
  recipe-maintainers:
    - atztogo
    - jochym
    - ttadano
